# Generated by Django 5.0.4 on 2024-07-30 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
