# Generated by Django 5.0.4 on 2024-07-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movie_is_awarded_alter_director_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
