# Generated by Django 5.0.4 on 2024-07-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_actor_last_update_alter_movie_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
