# Generated by Django 5.0.4 on 2024-07-21 11:08

from django.db import migrations

import random

from django.db import migrations, models


def add_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()
    barcodes = random.sample(
        range(100000000, 999999999),
        len(all_products)
    )

    for i in range(len(all_products)):
        product = all_products[i]
        product.barcode = barcodes[i]
        product.save()


def reverse_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    for product in Product.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0006_product_barcode'),
    ]

    operations = [migrations.RunPython(add_barcode,
                                       reverse_code=reverse_barcode, )
                  ]
