# Generated by Django 5.0.4 on 2024-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dragon_modified_at_alter_dragon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
