# Generated by Django 5.0.4 on 2024-07-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_menu_restaurant_alter_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.restaurant'),
            preserve_default=False,
        ),
    ]
